apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    server {
      listen 80;
      server_name example.com;
      
      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
    }
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Welcome to Nginx</title>
    </head>
    <body>
      <h1>Welcome to Nginx!</h1>
      <p>If you see this page, the nginx web server is successfully installed.</p>
    </body>
    </html>
